// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phoenix.DataHandle.Main.Models;

#nullable disable

namespace Phoenix.DataHandle.Migrations
{
    [DbContext(typeof(PhoenixContext))]
    [Migration("20220408204626_V3_alpha")]
    partial class V3_alpha
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserRoles");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Attendance", b =>
                {
                    b.Property<int>("AttendeeId")
                        .HasColumnType("int");

                    b.Property<int>("LectureId")
                        .HasColumnType("int");

                    b.HasKey("AttendeeId", "LectureId")
                        .HasName("PK_Attendance");

                    b.HasIndex(new[] { "LectureId" }, "IX_Attendance_LectureId");

                    b.HasIndex(new[] { "AttendeeId" }, "IX_Attendance_StudentId");

                    b.ToTable("Attendances", (string)null);
                });

            modelBuilder.Entity("BroadcastCourse", b =>
                {
                    b.Property<int>("BroadcastId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("BroadcastId", "CourseId")
                        .HasName("PK_BroadcastCourse");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "BroadcastId" }, "IX_BroadcastCourse");

                    b.ToTable("BroadcastCourses", (string)null);
                });

            modelBuilder.Entity("CourseBook", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "BookId")
                        .HasName("PK_CourseBook");

                    b.HasIndex("BookId");

                    b.HasIndex(new[] { "CourseId" }, "IX_CourseBook_CourseId");

                    b.ToTable("CourseBooks", (string)null);
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex(new[] { "CourseId" }, "IX_CourseUsers_CourseId");

                    b.HasIndex(new[] { "UserId" }, "IX_CourseUsers_UserId");

                    b.ToTable("CourseUsers", (string)null);
                });

            modelBuilder.Entity("Parenthood", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.HasKey("ParentId", "ChildId")
                        .HasName("PK_Parenthood");

                    b.HasIndex(new[] { "ChildId" }, "IX_Parenthood_ChildId");

                    b.HasIndex(new[] { "ParentId" }, "IX_Parenthood_ParentId");

                    b.ToTable("Parenthoods", (string)null);
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.AspNetRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.AspNetUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedApplicationType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((-1))");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ObviatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("PhoneNumberDependanceOrder")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumberVerificationCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("PhoneNumberVerificationCodeCreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PhoneNumber", "PhoneNumberDependanceOrder" }, "IX_AspNetUsers_Phone")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "UQ_AspNetUsers_UserName")
                        .IsUnique();

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.AspNetUserLogin", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("UserId", "ChannelId");

                    b.HasIndex(new[] { "ChannelId", "ProviderKey" }, "IX_AspNetUserLogins")
                        .IsUnique();

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "IX_Book")
                        .IsUnique();

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.BotFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AskTriggered")
                        .HasColumnType("bit");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("BotFeedback", (string)null);
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Broadcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Audience")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<int>("Daypart")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ScheduledDate")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AuthorId", "ScheduledDate" }, "IX_Broadcast_AuthorId_Date");

                    b.HasIndex(new[] { "ScheduledDate", "Daypart" }, "IX_Broadcast_Date_Daypart");

                    b.HasIndex(new[] { "SchoolId", "ScheduledDate" }, "IX_Broadcast_SchoolId_Date");

                    b.ToTable("Broadcasts");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code" }, "UQ_Channel_Code")
                        .IsUnique();

                    b.HasIndex(new[] { "Provider" }, "UQ_Channel_Provider")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("ObviatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SchoolId", "NormalizedName" }, "IX_Classroom")
                        .IsUnique();

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<short>("Code")
                        .HasColumnType("smallint");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTimeOffset>("FirstDate")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("LastDate")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("ObviatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<string>("SubCourse")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SchoolId", "Code" }, "IX_Course")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<int>("LectureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LectureId" }, "IX_Exam");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LectureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Page")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex(new[] { "LectureId" }, "IX_Exercise_LectureId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<int?>("ExamId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CourseId" }, "IX_Grades_Course");

                    b.HasIndex(new[] { "ExamId" }, "IX_Grades_Exam");

                    b.HasIndex(new[] { "ExerciseId" }, "IX_Grades_Exercise");

                    b.HasIndex(new[] { "StudentId" }, "IX_Grades_Student");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AttendancesNoted")
                        .HasColumnType("bit");

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EndDateTime")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("OnlineMeetingLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex(new[] { "CourseId" }, "IX_Lecture_CourseId");

                    b.HasIndex(new[] { "ScheduleId" }, "IX_Lecture_ScheduleId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Chapter")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex(new[] { "ExamId" }, "IX_Material_ExamId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset?>("ObviatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex(new[] { "CourseId", "DayOfWeek", "StartTime" }, "IX_Schedule")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("ObviatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code" }, "IX_School")
                        .IsUnique();

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.SchoolInfo", b =>
                {
                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.Property<string>("PrimaryLanguage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimaryLocale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.Property<string>("SecondaryLanguage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecondaryLocale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SchoolId")
                        .HasName("PK_SchoolSettings");

                    b.ToTable("SchoolInfo", (string)null);
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.SchoolLogin", b =>
                {
                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.HasKey("SchoolId", "ChannelId")
                        .HasName("PK_SchoolChannel");

                    b.HasIndex(new[] { "ChannelId", "ProviderKey" }, "IX_SchoolChannel")
                        .IsUnique();

                    b.ToTable("SchoolLogins");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.User", b =>
                {
                    b.Property<int>("AspNetUserId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IdentifierCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset?>("IdentifierCodeCreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<bool>("IsSelfDetermined")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("bit");

                    b.HasKey("AspNetUserId")
                        .HasName("PK_User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SchoolUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SchoolId")
                        .HasName("PK_UserSchool");

                    b.HasIndex(new[] { "SchoolId" }, "IX_UserSchool_SchoolId");

                    b.ToTable("SchoolUsers", (string)null);
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserRoles_AspNetRoles");

                    b.HasOne("Phoenix.DataHandle.Main.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserRoles_AspNetUsers");
                });

            modelBuilder.Entity("Attendance", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_AspNetUsers");

                    b.HasOne("Phoenix.DataHandle.Main.Models.Lecture", null)
                        .WithMany()
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Lecture");
                });

            modelBuilder.Entity("BroadcastCourse", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.Broadcast", null)
                        .WithMany()
                        .HasForeignKey("BroadcastId")
                        .IsRequired()
                        .HasConstraintName("FK_BroadcastCourse_Broadcast");

                    b.HasOne("Phoenix.DataHandle.Main.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_BroadcastCourse_Course");
                });

            modelBuilder.Entity("CourseBook", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CourseBook_Book");

                    b.HasOne("Phoenix.DataHandle.Main.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CourseBook_Course");
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseUsers_Courses");

                    b.HasOne("Phoenix.DataHandle.Main.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseUsers_AspNetUsers");
                });

            modelBuilder.Entity("Parenthood", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .IsRequired()
                        .HasConstraintName("FK_Parenthood_AspNetUsers_Child");

                    b.HasOne("Phoenix.DataHandle.Main.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_Parenthood_AspNetUsers_Parent");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.Channel", "Channel")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("ChannelId")
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserLogins_Channel");

                    b.HasOne("Phoenix.DataHandle.Main.Models.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserLogins_AspNetUsers");

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.BotFeedback", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.AspNetUser", "Author")
                        .WithMany("BotFeedbacks")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_BotFeedback_AspNetUsers");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Broadcast", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.AspNetUser", "Author")
                        .WithMany("Broadcasts")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_Broadcast_AspNetUsers");

                    b.HasOne("Phoenix.DataHandle.Main.Models.School", "School")
                        .WithMany("Broadcasts")
                        .HasForeignKey("SchoolId")
                        .IsRequired()
                        .HasConstraintName("FK_Broadcast_School");

                    b.Navigation("Author");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Classroom", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.School", "School")
                        .WithMany("Classrooms")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Classroom_School");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Course", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.School", "School")
                        .WithMany("Courses")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Course_School");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Exam", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.Lecture", "Lecture")
                        .WithMany("Exams")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Exam_Lecture");

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Exercise", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.Book", "Book")
                        .WithMany("Exercises")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Exercise_Book");

                    b.HasOne("Phoenix.DataHandle.Main.Models.Lecture", "Lecture")
                        .WithMany("Exercises")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Exercise_Lecture");

                    b.Navigation("Book");

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Grade", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.Course", "Course")
                        .WithMany("Grades")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_Grades_Courses");

                    b.HasOne("Phoenix.DataHandle.Main.Models.Exam", "Exam")
                        .WithMany("Grades")
                        .HasForeignKey("ExamId")
                        .HasConstraintName("FK_Grades_Exams");

                    b.HasOne("Phoenix.DataHandle.Main.Models.Exercise", "Exercise")
                        .WithMany("Grades")
                        .HasForeignKey("ExerciseId")
                        .HasConstraintName("FK_Grades_Exercises");

                    b.HasOne("Phoenix.DataHandle.Main.Models.AspNetUser", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Grades_AspNetUsers");

                    b.Navigation("Course");

                    b.Navigation("Exam");

                    b.Navigation("Exercise");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Lecture", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.Classroom", "Classroom")
                        .WithMany("Lectures")
                        .HasForeignKey("ClassroomId")
                        .HasConstraintName("FK_Lecture_Classroom");

                    b.HasOne("Phoenix.DataHandle.Main.Models.Course", "Course")
                        .WithMany("Lectures")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Lecture_Course");

                    b.HasOne("Phoenix.DataHandle.Main.Models.Schedule", "Schedule")
                        .WithMany("Lectures")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Lecture_Schedule");

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Material", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.Book", "Book")
                        .WithMany("Materials")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Material_Book");

                    b.HasOne("Phoenix.DataHandle.Main.Models.Exam", "Exam")
                        .WithMany("Materials")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Material_Exam");

                    b.Navigation("Book");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Schedule", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.Classroom", "Classroom")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Schedule_Classroom");

                    b.HasOne("Phoenix.DataHandle.Main.Models.Course", "Course")
                        .WithMany("Schedules")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Course");

                    b.Navigation("Classroom");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.SchoolInfo", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.School", "School")
                        .WithOne("SchoolInfo")
                        .HasForeignKey("Phoenix.DataHandle.Main.Models.SchoolInfo", "SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SchoolSettings_School");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.SchoolLogin", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.Channel", "Channel")
                        .WithMany("SchoolLogins")
                        .HasForeignKey("ChannelId")
                        .IsRequired()
                        .HasConstraintName("FK_SchoolLogins_Channel");

                    b.HasOne("Phoenix.DataHandle.Main.Models.School", "School")
                        .WithMany("SchoolLogins")
                        .HasForeignKey("SchoolId")
                        .IsRequired()
                        .HasConstraintName("FK_SchoolLogins_School");

                    b.Navigation("Channel");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.User", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.AspNetUser", "AspNetUser")
                        .WithOne("User")
                        .HasForeignKey("Phoenix.DataHandle.Main.Models.User", "AspNetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_AspNetUsers");

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("SchoolUser", b =>
                {
                    b.HasOne("Phoenix.DataHandle.Main.Models.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSchool_School");

                    b.HasOne("Phoenix.DataHandle.Main.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSchool_AspNetUsers");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserLogins");

                    b.Navigation("BotFeedbacks");

                    b.Navigation("Broadcasts");

                    b.Navigation("Grades");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Book", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Channel", b =>
                {
                    b.Navigation("AspNetUserLogins");

                    b.Navigation("SchoolLogins");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Classroom", b =>
                {
                    b.Navigation("Lectures");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Course", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Lectures");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Exam", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Exercise", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Lecture", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.Schedule", b =>
                {
                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("Phoenix.DataHandle.Main.Models.School", b =>
                {
                    b.Navigation("Broadcasts");

                    b.Navigation("Classrooms");

                    b.Navigation("Courses");

                    b.Navigation("SchoolInfo")
                        .IsRequired();

                    b.Navigation("SchoolLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
